version: "3.2"

services:
  backend:
    image: vinimrs/netflix-backend
    environment:
      TZ: America/Sao_Paulo
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        # change the host here
        - "traefik.http.routers.backend.rule=Host(`netbackend.vinimrs.dev`)"
        - "traefik.http.services.backend.loadbalancer.server.port=3333"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=leresolver"

networks:
  traefik-public:
    driver: overlay
    external: true