- hosts: netflix-backend
  tasks:
    - name: install dependencies
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - git-all
        state: latest
        update_cache: yes
    - name: GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: repository docker
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: install docker
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    - name: adding users to group docker
      become: true
      user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop:
        - ubuntu
    - name: Install docker-compose
      become: true
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
    - name: Removing previous folder
      shell: 'rm -rf /home/ubuntu/netflix-backend'
    - name: Clone a github repository
      git:
        repo: https://github.com/vinimrs/netflix-backend.git
        dest: /home/ubuntu/netflix-backend
        clone: yes
        update: yes
    # - name: Criando pasta
    #   shell: 'mkdir /home/ubuntu/netflix-backend'
    #   ignore_errors: yes
    # - name: Copying compose file
    #   copy:
    #     src: ./compose.yaml
    #     dest: /home/ubuntu/netflix-backend/
    - name: Copying env file
      copy:
        src: ./.env
        dest: /home/ubuntu/netflix-backend/
    - name: Initializing the project
      shell: 'cd /home/ubuntu/netflix-backend && sudo service docker start && sudo docker-compose up -d'
      ignore_errors: yes

