- hosts: netflix-backend
  tasks:
    - name: Build app locally
      tags: app, build, deploy
      shell: npm run build
      args:
        chdir: ./
      delegate_to: 127.0.0.1
    
    - name: Creating project folder
      shell: 'rm -rf /home/ubuntu/netflix-backend && mkdir /home/ubuntu/netflix-backend'

    - name: Copy build to server
      tags: app, build, deploy
      copy:
        src: ./dist
        dest: /home/ubuntu/netflix-backend/
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Copy package-lock.json to server
      tags: app, build, deploy
      copy:
        src: ./package-lock.json
        dest: /home/ubuntu/netflix-backend/package-lock.json
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Copy package.json to server
      tags: app, build, deploy
      copy:
        src: ./package.json
        dest: /home/ubuntu/netflix-backend/package.json
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Copying env file
      copy:
        src: ./.env
        dest: /home/ubuntu/netflix-backend/

    - name: Install dependencies from lockfile
      tags: app, build, deploy
      shell: npm ci
      args:
        chdir: /home/ubuntu/netflix-backend/

    - name: Restarting the app 
      shell: pm2 restart 0
