- hosts: netflix_backend
  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install GPG
      become: true
      tags: nodejs, install, setup
      apt:
        name: gnupg
        update_cache: yes
        state: present

    - name: Install the gpg key for nodejs LTS
      become: true
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      become: true
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x focal main"
        state: present
        update_cache: yes

    - name: Install NodeJS
      become: true
      tags: nodesjs, install
      apt:
        name: nodejs
        state: latest

    - name: Installing Nginx
      become: true
      tags: nginx, install
      apt:
        name: nginx

    - name: Installing PM2
      become: true
      shell: npm install pm2@latest -g
      
    - name: Stopping apache2
      become: true
      shell: service apache2 stop
      ignore_errors: true
    
    - name: Inserting location config
      become: true
      blockinfile:
        dest: /etc/nginx/sites-available/default
        block: |
          proxy_pass http://localhost:3333;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        backup: yes
        insertafter: '^\s*location \/ {$'
    
    - name: Inserting server_name config 
      become: true
      lineinfile:
        dest: /etc/nginx/sites-available/default
        line: server_name localhost vinimrs.dev netbackend.vinimrs.dev;
        insertafter: server_name _;
    
    - name: Removing previous nginx location config
      become: true
      lineinfile:
          regexp: '^\s*try_files \$uri \$uri\/ =404;$'
          path: /etc/nginx/sites-available/default
          state: absent

    - name: Removing previous nginx server_name config
      become: true
      lineinfile:
          regexp: '^\s*server_name _;$'
          path: /etc/nginx/sites-available/default
          state: absent
    
    - name: Check nginx config
      become: true
      shell: nginx -t

    - name: Restart nginx
      become: true
      shell: service nginx restart

    - name: Installing core
      become: true
      shell: snap install core && snap refresh core
    
    - name: Removing Certbot
      become: true
      shell: apt remove certbot

    - name: Installing Certbot
      become: true
      shell: snap install --classic certbot
    
    - name: Updating the certbot link
      become: true
      shell: ln -s /snap/bin/certbot /usr/bin/certbot

    - name: Confirming Nginx’s Configuration
      become: true
      shell: systemctl reload nginx

    - name: Obtaining an free ssl certificate
      become: true
      shell: certbot --nginx -d netbackend.vinimrs.dev --non-interactive --agree-tos -m viniromualdo082@gmail.com

    - name: Verifying Certbot auto-renewal
      become: true
      shell: systemctl status snap.certbot.renew.service
      ignore_errors: true