name: Continuous integration (ESLint & Prettier)

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']


jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: npm i
      - name: Run linter
        run: npm run lint:fix
        
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: npm i
      - name: Run formatter
        run: npm run prettier